### ISSUE TITLE
Add `getInputBox` function to `ICartesiDApp`

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#149]
## 📚 Context

There should be an entry point for outsiders to know which input box is the DApp listening to. This may be particularly useful for consensuses.

## ✔️ Solution

Add a `getInputBox` function that returns the address of the input box where inputs to the DApp should be added to.

## 📈 Subtasks

- [ ] Add function to `ICartesiDApp` and `CartesiDApp`
- [ ] Add parameter to `CartesiDApp` constructor
- [ ] Add parameter to functions and events from `ICartesiDAppFactory` and `CartesiDApp`
- [ ] Add unit tests

**Comment by guidanoli** [comment]
FYI @tuler
