### ISSUE TITLE
Add `getInputRelays` function to `ICartesiDApp`

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#150]
## 📚 Context

There should be an entry point where outsiders can know which contracts the DApp back-end is expecting inputs from. These contracts are called input relays. Most input relays also deal with assets, such as Ether and ERC-20 tokens.

## ✔️ Solution

Add a `getSupportedInputRelays` function to `ICartesiDApp` which returns an array of addresses from which the DApp back-end expects inputs from. Off-chain components such as the node CLI will be able to tell the type of input relay by calling the `supportsInterface` function on each input relay address. These addresses may even be typed as [`IERC165`](https://eips.ethereum.org/EIPS/eip-165) from OpenZeppelin to help the node make these calls seamlessly without type casts.

```solidity
function getInputRelays() external view returns (address[] memory);
```

The list of supported input relays will be decided on construction.

## 📈 Subtasks

- [ ] Add an `address[]` parameter to the function and events of `CartesiDAppFactory` and `ICartesiDApp`
- [ ] Add an `address[]` parameter to the `CartesiDApp` constructor
- [ ] Adjust `CartesiDAppFactory` to instantiate `CartesiDApp` properly
- [ ] Add a `getInputRelays` function to `ICartesiDApp` and `CartesiDApp`
- [ ] Add unit tests
