### ISSUE TITLE
Migrate from `yarn` to `pnpm`

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#249]
## 📚 Context

We've been using `yarn` to manage JavaScript/TypeScript dependencies since the beginning.
There are other Node package managers available. One of those is [`pnpm`](https://pnpm.io/).
There are many reasons to migrate from `yarn` to `pnpm`. See [motivations](https://pnpm.io/motivation).

## ✔️ Solution

Migrate to `pnpm`

## 📈 Subtasks

- [ ] Delete the `yarn.lock` file
- [ ] Run `pnpm i` to create a `pnpm-lock.yaml` file
- [ ] Fix GitHub workflow files to use `pnpm`
- [ ] Fix commands in the README
