### ISSUE TITLE
Migrate from yarn "classic" (1.x) to "modern" (3.x)

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#40]
## 📚 Context

We are currently using `yarn` "classic" (1.x) to manager our JavaScript dependencies.
There are, however, [several benefits](https://yarnpkg.com/migration/overview) in migrating to "modern" (3.x).

## 📈 Subtasks

According to the [official step-by-step list](https://yarnpkg.com/migration/guide)...

- [x] Make sure you're using Node 18+
- [x] Run `corepack enable` to activate [Corepack](https://nodejs.org/api/corepack.html)
- [x] Go into your project directory
- [x] Run `yarn set version berry` [[?]](https://yarnpkg.com/cli/set/version)
- [x] Convert your `.npmrc` and `.yarnrc` files into `.yarnrc.yml` [[?]](https://yarnpkg.com/configuration/yarnrc) (details [here](https://yarnpkg.com/migration/guide#update-your-configuration-to-the-new-settings))
- [x] Run `yarn install` [[?]](https://yarnpkg.com/cli/install) to migrate the lockfile
- [x] Commit all changes

Additionally, we should...
- [x] Update the link in the README to point to the [new installation page](https://yarnpkg.com/getting-started/install).
- [x] Check if we need to update any steps in the dependency bump issue template.
- [x] Update workflow files to install and set up the correct version of `yarn`.
- [x] Update `.gitignore` files to include any new folders or files that should be ignored.

**Comment by tuler** [comment]
I support the change. Including migrating to PnP.
Just watch out for places where you read file directory from `node_modules`, like in the hardhat/foundry integration.

**Comment by xdaniortega** [comment]
> I support the change. Including migrating to PnP.
> Just watch out for places where you read files directly from `node_modules`, like in the hardhat/foundry integration.

I'm having difficulties replacing the node_modules references to integrate and use the new PnP feature.
I don't know exactly how to import the packages from node_modules in the solidity code.

I already added the `@openzeppelin` and `@cartesi` packages with yarn and I can find them at `onchain/.yarn/cache/@openzeppelin-contracts-npm-4.9.3-5ad99d59ab-4932063e73.zip` but no way to access the desired contract inside like:
`.yarn/cache/@openzeppelin-contracts-npm-4.9.3-5ad99d59ab-4932063e73.zip/node_modules/@openzeppelin/`

Do you have any idea?

**Comment by xdaniortega** [comment]
> One alternative is to use `forge` to manage smart contract dependencies, through git submodules. See [`forge install`](https://book.getfoundry.sh/reference/forge/forge-install).

Do you think is the best alternative? My only concern is that we use `foundry` for testing, and now foundry will be in charge for installing some dependencies also.

**Comment by guidanoli** [comment]
> My only concern is that we use foundry for testing, and now foundry will be in charge for installing some dependencies also.

Why should that be a concern? The dependencies themselves will be git modules, so you wouldn't actually need `forge` to download them.

**Comment by xdaniortega** [comment]
> > My only concern is that we use foundry for testing, and now foundry will be in charge for installing some dependencies also.
> 
> The dependencies themselves will be git modules, so you wouldn't actually need `forge` to install them.

I saw there's no git repo for openzeppelin contracts, so there's no possibility to add it as a submodule, just npm. :(

**Comment by xdaniortega** [comment]
Should we just update yarn version without PnP? I see there are some things that are not replaceable for this feature.
- NPM package of Openzepellin contracts.
- Yarn script `fmt:check` errors bc of prettier. 
@guidanoli @tuler .

**Comment by guidanoli** [comment]
> I saw there's no git repo for openzeppelin contracts

https://github.com/OpenZeppelin/openzeppelin-contracts
