### ISSUE TITLE
Propose ENS to community

### ISSUE THREAD

**Issue by xdaniortega** [cartesi/rollups-contracts#69]
## 📚 Context

We're considering the possibility to integrate an ENS resolver inside Cartesi Rollups (CR), this feature can have several implications on development, allowing decentralized identities inside CR, universal logins and account sovereign for games developed with the Cartesi SDK. Additionally, it could reduce the bytes reserved in a voucher for the destination address.

As this feature can have a positive impact for the gamers and developers community, we can do a small voting or announcement to improve the communication with our community, demonstrate active development and integrate developer feedback in our ideas. It's an easy implementation that should not have a lot of implication and difficulties from other units.

## ✔️ Solution

Sync with Marketing Unit, introduce the possible features and coordinate for a proposal to gamers and developers to see how much engagement we can achieve and feedback.

## 📈 Subtasks

- [ ] Sum up all benefits for ENS integration.
- [ ] Propose Marketing Unit.
- [ ] Write a small RFP to be analyzed by the foundation.
- [ ] Sync specific proposal to the community after approval.

**Comment by tuler** [comment]
It’s not clear to me what this is issue is about.

**Comment by xdaniortega** [comment]
Hello @tuler, we were discussing to integrate ENS name resolving in Cartesi. Despite the technology-wise discussion is still going on, we came across the idea that after confirming the viability of the feature, it'll really cool to ask developers and gamers if they love the idea or not to integrate ENS as tags for games and so on.

This feature, which we already know how useful it could be, could have a good impact in terms of visibility and further engage developers to use our stack, we will improve the communication with the community and get feedback about this feature.

**Comment by guidanoli** [comment]
The `no changelog` label is only for PRs that do not change the changelog.

**Comment by guidanoli** [comment]
> Additionally, it could reduce the bytes reserved in a voucher for the destination address.

Probably not, given that, using standard ABI encoding, addresses occupy at least 20 bytes, and strings with $n$ characters occupy at least $n+64$ bytes.

**Comment by xdaniortega** [comment]
@guidanoli thanks for the feedback, here I just made a summary of all the conversations we've been having about this feature, this issue is the status and the discussion on wether or not introduce the feature to the community. 

Please for technology-wise aspects you can continue [here](https://github.com/cartesi/rollups-contracts/issues/58).

**Comment by ZzzzHui** [comment]
> > Additionally, it could reduce the bytes reserved in a voucher for the destination address.
> 
> Probably not, given that, using standard ABI encoding, addresses occupy at least 20 bytes, and strings with n characters occupy at least n+64 bytes.

ENS names are usually [hashed into 32 bytes](https://docs.ens.domains/contract-api-reference/name-processing). For standard abi encoding, `bytes32` and `address` occupy the same amount of storage.

**Comment by guidanoli** [comment]
> ENS names are usually [hashed into 32 bytes](https://docs.ens.domains/contract-api-reference/name-processing). For standard abi encoding, bytes32 and address occupy the same amount of storage.

Good point. Maybe in the registration process, the input will have to encode the full string, but on future interactions, it can contain only the hash, right?

**Comment by ZzzzHui** [comment]
We only need to work with the resolution process, right? The ENS registry and resolvers mostly work with hashes like the following, and we leave the hash calculation offchain
```
abstract contract ENS {
    function resolver(bytes32 node) public virtual view returns (Resolver);
}

abstract contract Resolver {
    function addr(bytes32 node) public virtual view returns (address);
}
```
reference: https://docs.ens.domains/contract-developer-guide/resolving-names-on-chain

**Comment by xdaniortega** [comment]
This issue is blocked until #58 is done.
