### ISSUE TITLE
Migrate to Yarn PNP (Plug’n’Play) for package installation

### ISSUE THREAD

**Issue by xdaniortega** [cartesi/rollups-contracts#92]
## 📚 Context

With the update from yarn version 1.x to 3.6.3 (berry) we can migrate and use Yarn PnP, this will allow to use the latest way to manage packages, as well as, get rid of node_modules folder and loading a self-generated `.pnp.cjs` with the routed of all package locations and dependencies.

This issue follows issue #75 introduced by @guidanoli and this migration was suggested by @tuler.

## 📈 Subtasks

Please follow  yarn [guide](https://yarnpkg.com/migration/pnp) here.
- [x] Look into your `.yarnrc.yml` file for the [nodeLinker](https://yarnpkg.com/configuration/yarnrc#nodeLinker) setting.
- [x] Set to `pnp`
- [x] Commit the changes.
- [x] Check there are no node_modules folders
- [x] Adapt existing imports from node_modules (f.e openzeppelin)
- [x] Custom pre-hooks (e.g. prestart) need to be called manually now (yarn prestart).
