### ISSUE TITLE
Updating `CHANGELOG` is cumbersome

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#94]
## 📚 Context

Currently, we're updating the `CHANGELOG` file every time we introduce a change.
We've noticed, however, that this strategy creates the following issues:

- Contributors often need to resolve merge conflicts in the `CHANGELOG` file.
- Contributors might not know in which release any given change should be introduced.

## ✔️ Solution

[Changesets](https://github.com/changesets/changesets) help manage versioning and changelogs with a CLI tool, bot and workflow action.
Take a look at how [Sunodo](https://github.com/sunodo/sunodo) is using changesets to manage the various packages inside their monorepo.
Of course, in our specific case, changesets would only manage `@cartesi/rollups`, which is fine.
Also, instead of maintaining a `CHANGELOG` file manually, we can use `changesets` to generate changelogs and have them published in the release notes on GitHub. This process can be automated in the CI.
PRs that update the `CHANGELOG` file should use `changesets` instead.

## 📈 Subtasks

- [x] Add the `changesets` CLI to the list of NPM dependencies and configure it. See the [step-by-step guide](https://www.npmjs.com/package/@changesets/cli).
- [x] Configure the `changesets` bot through [here](https://github.com/apps/changeset-bot).
- [x] Update the CI to use [`changesets/action`](https://github.com/changesets/action).

**Comment by guidanoli** [comment]
This is not done yet!
