### ISSUE TITLE
Unnecessary compartmentalization

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#95]
## 📚 Context

Not long ago, the on-chain code was part of a repository that also contained off-chain code.
As to avoid mixing the two, they were each put in their own directory.

This is, however, no longer the case, with the on-chain code having its own repository!
This allows us to bring the on-chain code out of its directory, saving us keystrokes when navigating the repository.

Moreover, the permissionless arbitration code has been effectively moved to its own repository, [`cartesi/dave`](https://github.com/cartesi/dave).
This allows us to remove the `onchain/rollups-arbitration` directory, and bring everything inside `onchain/rollups` to the root of the repository.

## ✔️ Solution

Move every file inside `onchain/rollups` to the root of the repository.

## 📈 Subtasks

- [ ] Move everything inside `onchain/rollups` to the root of the repository
- [ ] Fix any references to the `onchain` directory
- [ ] Turn the `changesets` bot back on
